services:
    database:
        image: 'mysql:9'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: friendevent
        ports:
            - '3306'
        volumes:
            - 'mysql_data:/var/lib/mysql'
    backend:
        build: .
        ports:
            - '8082:80'

volumes:
    mysql_data:

